### ISSUE TITLE
Compilation errors with zig 0.8.0

### ISSUE THREAD

**Issue by greenfork** [q60/tuatara#1]
```
./src/main.zig:122:29: error: expected type '[]const u8', found 'type'
    var home = mem.tokenize(u8, os.getenv("HOME").?, fs.path.sep_str);
```

You probably want to specify the commit hash of the zig compiler to build with or to rewrite it for the latest stable version.

**Comment by q60** [comment]
@greenfork 

resolved with 11bc4d65521c7c7fee4d47429a85788f7409057e.
https://github.com/q60/tuatara/releases/tag/1630857893
