### ISSUE TITLE
Building with Zig 0.8.1

### ISSUE THREAD

**Issue by Enqueued** [q60/tuatara#2]
`./src/main.zig:130:29: error: expected type '[]const u8', found 'type'
    var home = mem.tokenize(u8, os.getenv("HOME").?, fs.path.sep_str);
                            ^
/usr/lib/zig/std/start.zig:471:40: note: referenced here
            const result = root.main() catch |err| {`
            
This was built on Fedora 34.

**Comment by q60** [comment]
meow

**Comment by q60** [comment]
@Enqueued resolved in #3
